Raise helpful errors for DSL section inline and inline+block syntax
Currently DSL sections throw confusing error messages for the following DSL declarations:

1. Using inline keyword args instead of block syntax gives

```
** (Spark.Options.ValidationError) required :first_name option not found, received options: []
```

2. Using inline and block syntax throws the following compile error

```
error: undefined function section_name/2 (there is no such import)
```

We now catch these errors and show helpful errors so that the user understands what went wrong and how to fix it. The new errors are as follows:

1. Inline syntax
```
Cannot use inline syntax for DSL section `personal_details`. Use block syntax: `personal_details do ... end`.
```

2. Mixed inline and block syntax
```
Cannot use both inline syntax and block syntax for DSL section `personal_details`. Use block syntax `personal_details do ... end`
```